
import { GlobalSettings, VehicleConfig, Client, SavedLocation, TariffItem } from './types';
import { IMPORTED_CLIENTS } from './data/clients';

export const VEHICLES: VehicleConfig[] = [
  {
    id: 'voiture',
    name: 'Voiture',
    description: 'Coursier Standard',
    image: '',
    base_price: 15.0,
    price_per_km: 1.5,
    price_per_minute: 0.30,
  },
  {
    id: 'camionnette',
    name: 'Camionnette',
    description: 'Volume Supérieur',
    image: '',
    base_price: 25.0,
    price_per_km: 2.0,
    price_per_minute: 0.40,
  }
];

export const ZONES = [
  { id: 1, name: 'Zone 1 (Gare Centrale, Centre-Ville, Limpertsberg)', price: 12.22, traversesLux: true },
  { id: 2, name: 'Zone 2 (Merl, Belair, Rollingergrund, Clausen, Bonnevoie, Hollerich, CSSF)', price: 13.77, traversesLux: true },
  { id: 3, name: 'Zone 3 (Rte d\'Arlon (Lux.), Rte de Longwy (Lux.))', price: 15.09, traversesLux: true },
  { id: 4, name: 'Zone 4 (Cloche d\'Or, Gasperich, Howald)', price: 15.65, traversesLux: true },
  { id: 5, name: 'Zone 5 (Kirchberg, Neudorf)', price: 16.64, traversesLux: false },
  { id: 6, name: 'Zone 6 (Cents, Hamm, Weimerskirch, Hesperange)', price: 17.30, traversesLux: true },
];

export const SPECIAL_ROUTES = [
  { id: 'kirchberg_apostille', name: 'Kirchberg -> Apostille', price: 13.30 },
  { id: 'sennigerberg_apostille', name: 'Sennigerberg -> Apostille', price: 18.30 },
  { id: 'cloche_apostille', name: 'Cloche -> Apostille', price: 12.40 },
  { id: 'hellinckx_apostille', name: 'Hellinckx -> Apostille', price: 13.90 },
  { id: 'cloche_sennigerberg', name: 'Cloche -> Sennigerberg', price: 20.00 },
  { id: 'cloche_kirchberg', name: 'Cloche -> Kirchberg', price: 15.00 },
  { id: 'cloche_wersandt', name: 'Cloche -> Wersandt', price: 19.10 },
  { id: 'ar_ville', name: 'Aller Retour Ville', price: 13.80 },
  { id: 'ar_kirchberg', name: 'Aller Retour Kirchberg', price: 21.80 },
];

export const FIXED_DESTINATIONS = [
  { id: 'abweiler', name: 'Abweiler (Luxembourg)', price: 30.30 },
  { id: 'algrange', name: 'Algrange (France)', price: 71.54 },
  { id: 'allondrelle', name: 'Allondrelle-La-Malmaison (France)', price: 108.63 },
  { id: 'altwies', name: 'Altwies (Luxembourg)', price: 46.05 },
  { id: 'alzingen', name: 'Alzingen (Luxembourg)', price: 23.09 },
  { id: 'amneville', name: 'Amneville (France)', price: 87.44 },
  { id: 'arlon', name: 'Arlon (Belgique)', price: 67.52 },
  { id: 'asch', name: 'Asch (Luxembourg)', price: 59.51 },
  { id: 'aspelt', name: 'Aspelt (Luxembourg)', price: 44.28 },
  { id: 'assel', name: 'Assel (Luxembourg)', price: 42.76 },
  { id: 'athus', name: 'Athus (Belgique)', price: 50.24 },
  { id: 'attert', name: 'Attert (Belgique)', price: 77.84 },
  { id: 'aubange', name: 'Aubange (Belgique)', price: 57.08 },
  { id: 'bascharage', name: 'Bascharage (Luxembourg)', price: 42.29 },
  { id: 'basebellain', name: 'Basebellain (Luxembourg)', price: 154.44 },
  { id: 'basse_rentgen', name: 'Basse Rentgen (France)', price: 58.41 },
  { id: 'bastogne', name: 'Bastogne (Belgique)', price: 126.73 },
  { id: 'beaufort', name: 'Beaufort (Luxembourg)', price: 74.47 },
  { id: 'bech', name: 'Bech (Luxembourg)', price: 62.71 },
  { id: 'bech_kleinmacher', name: 'Bech-Kleinmacher (Luxembourg)', price: 51.34 },
  { id: 'beckerich', name: 'Beckerich (Luxembourg)', price: 70.77 },
  { id: 'beggen', name: 'Beggen (Luxembourg)', price: 23.09 },
  { id: 'beigem', name: 'Beigem (Belgique)', price: 401.80 },
  { id: 'bekond', name: 'Bekond (Allemagne)', price: 129.05 },
  { id: 'belvaux', name: 'Belvaux, Notaire Wagner', price: 42.08 },
  { id: 'berbourg', name: 'Berbourg (Luxembourg)', price: 65.47 },
  { id: 'berchem', name: 'Berchem (Luxembourg)', price: 31.92 },
  { id: 'berdorf', name: 'Berdorf (Luxembourg)', price: 59.18 },
  { id: 'bereldange', name: 'Bereldange (Luxembourg)', price: 24.85 },
  { id: 'bergem', name: 'Bergem (Luxembourg)', price: 37.22 },
  { id: 'beringen', name: 'Beringen (Luxembourg)', price: 46.05 },
  { id: 'bertrange_fr', name: 'Bertrange (France)', price: 78.61 },
  { id: 'bertrange_lux', name: 'Bertrange, Strassen (Luxembourg)', price: 18.85 },
  { id: 'bertrix', name: 'Bertrix (Belgique)', price: 138.66 },
  { id: 'bettange_mess', name: 'Bettange-sur-Mess (Luxembourg)', price: 33.79 },
  { id: 'bettborn', name: 'Bettborn (Luxembourg)', price: 66.14 },
  { id: 'bettembourg', name: 'Bettembourg (Luxembourg)', price: 28.61 },
  { id: 'betzdorf', name: 'Betzdorf (Luxembourg)', price: 42.62 },
  { id: 'beyren', name: 'Beyren (Luxembourg)', price: 46.05 },
  { id: 'bissen', name: 'Bissen (Luxembourg)', price: 50.35 },
  { id: 'bitbourg', name: 'Bitbourg (Allemagne)', price: 111.39 },
  { id: 'biwer', name: 'Biwer (Luxembourg)', price: 50.35 },
  { id: 'blaschette', name: 'Blaschette (Luxembourg)', price: 37.22 },
  { id: 'boevange_attert', name: 'Boevange-sur-attert (Luxembourg)', price: 55.65 },
  { id: 'bofferdange', name: 'Bofferdange (Luxembourg)', price: 30.15 },
  { id: 'boudler', name: 'Boudler (Luxembourg)', price: 56.64 },
  { id: 'bourscheid', name: 'Bourscheid (Luxembourg)', price: 78.61 },
  { id: 'bourscheide', name: 'Bourscheide (Luxembourg)', price: 81.37 },
  { id: 'boust', name: 'Boust (France)', price: 60.17 },
  { id: 'bovigny', name: 'Bovigny (Belgique)', price: 209.30 },
  { id: 'breidweiler', name: 'Breidweiler (Luxembourg)', price: 58.41 },
  { id: 'breistroff', name: 'Breistroff-la-Grande (France)', price: 50.87 },
  { id: 'bridel', name: 'Bridel (Luxembourg)', price: 25.74 },
  { id: 'brouch', name: 'Brouch (Luxembourg)', price: 53.11 },
  { id: 'bruxelles', name: 'Bruxelles (Belgique)', price: 277.96 },
  { id: 'burmerange', name: 'Burmerange (Luxembourg)', price: 48.58 },
  { id: 'canach', name: 'Canach (Luxembourg)', price: 29.16 },
  { id: 'carling', name: 'Carling (France)', price: 159.85 },
  { id: 'cattenom', name: 'Cattenom (France)', price: 74.30 },
  { id: 'chatillon', name: 'Chatillon (Belgique)', price: 76.95 },
  { id: 'christnach', name: 'Christnach (Luxembourg)', price: 48.58 },
  { id: 'clemency', name: 'Clemency (Luxembourg)', price: 48.58 },
  { id: 'clervaux', name: 'Clervaux (Luxembourg)', price: 115.70 },
  { id: 'colmarberg', name: 'Colmarberg (Luxembourg)', price: 54.99 },
  { id: 'colpach', name: 'Colpach (Luxembourg)', price: 73.27 },
  { id: 'consdorf', name: 'Consdorf (Luxembourg)', price: 50.57 },
  { id: 'contern', name: 'Contern (Luxembourg)', price: 28.34 },
  { id: 'crauthem', name: 'Crauthem (Luxembourg)', price: 29.82 },
  { id: 'cruchten', name: 'Cruchten (Luxembourg)', price: 57.42 },
  { id: 'dalheim', name: 'Dalheim (Luxembourg)', price: 36.77 },
  { id: 'diekirch', name: 'Diekirch (Luxembourg)', price: 63.66 },
  { id: 'differdange', name: 'Differdange (Luxembourg)', price: 53.11 },
  { id: 'dippach', name: 'Dippach (Luxembourg)', price: 33.79 },
  { id: 'distroff', name: 'Distroff (France)', price: 78.61 },
  { id: 'dommeldange', name: 'Dommeldange (Luxembourg)', price: 21.16 },
  { id: 'dudelange', name: 'Dudelange (Luxembourg)', price: 38.98 },
  { id: 'dusseldorf', name: 'Düsseldorf (Allemagne)', price: 421.23 },
  { id: 'ebly', name: 'Ebly (Belgique)', price: 120.72 },
  { id: 'echternach', name: 'Echternach (Luxembourg)', price: 63.04 },
  { id: 'ehlange_mess', name: 'Ehlange-sur-mess (Luxembourg)', price: 35.45 },
  { id: 'ehlerange', name: 'Ehlerange (Luxembourg)', price: 37.88 },
  { id: 'ehnen', name: 'Ehnen (Luxembourg)', price: 40.97 },
  { id: 'eischen', name: 'Eischen (Luxembourg)', price: 52.12 },
  { id: 'elvange', name: 'Elvange (Luxembourg)', price: 47.81 },
  { id: 'ernster', name: 'Ernster (Luxembourg)', price: 35.45 },
  { id: 'ersange', name: 'Ersange (Luxembourg)', price: 37.22 },
  { id: 'esch_alzette', name: 'Esch/Alzette, Notaire Meyers, Notaire Grethen', price: 40.48 },
  { id: 'esch_sure', name: 'Esch Sur Sure (Luxembourg)', price: 103.18 },
  { id: 'escherange', name: 'Escherange (France)', price: 60.17 },
  { id: 'esselborn', name: 'Esselborn (Luxembourg)', price: 126.29 },
  { id: 'etalle', name: 'Etalle (Belgique)', price: 92.76 },
  { id: 'ethe', name: 'Ethe (Belgique)', price: 92.74 },
  { id: 'ettelbruck', name: 'Ettelbruck (Luxembourg)', price: 54.99 },
  { id: 'famek', name: 'Famek (France)', price: 76.84 },
  { id: 'fell', name: 'Fell (Allemagne)', price: 110.40 },
  { id: 'fennange', name: 'Fennange (Luxembourg)', price: 28.61 },
  { id: 'fentange', name: 'Fentange (Luxembourg)', price: 23.09 },
  { id: 'fillieres', name: 'Fillières (France)', price: 77.84 },
  { id: 'flaxweiler', name: 'Flaxweiler (Luxembourg)', price: 42.62 },
  { id: 'florenville', name: 'Florenville (Belgique)', price: 139.65 },
  { id: 'foetz', name: 'Foetz (Luxembourg)', price: 37.22 },
  { id: 'francfort', name: 'Francfort (Allemagne)', price: 431.39 },
  { id: 'freudenburg', name: 'Freudenburg (Allemagne)', price: 66.02 },
  { id: 'frisange', name: 'Frisange (Luxembourg)', price: 35.67 },
  { id: 'gandrange', name: 'Gandrange (France)', price: 87.44 },
  { id: 'gavisse', name: 'Gavisse (France)', price: 70.77 },
  { id: 'goeblange', name: 'Goeblange (Luxembourg)', price: 37.22 },
  { id: 'gorcy', name: 'Gorcy (France)', price: 87.25 },
  { id: 'goseldange', name: 'Goseldange (Luxembourg)', price: 36.22 },
  { id: 'gostingen', name: 'Gostingen (Luxembourg)', price: 40.64 },
  { id: 'grass', name: 'Grass (Luxembourg)', price: 54.88 },
  { id: 'graulinster', name: 'Graulinster (Luxembourg)', price: 42.29 },
  { id: 'greisch', name: 'Greisch (Luxembourg)', price: 41.52 },
  { id: 'greiveldange', name: 'Greiveldange (Luxembourg)', price: 47.81 },
  { id: 'grevenknapp', name: 'Grevenknapp (Luxembourg)', price: 54.88 },
  { id: 'grevenmacher', name: 'Grevenmacher, Pétange, Notaire Kesseler', price: 54.17 },
  { id: 'grosbous', name: 'Grosbous (Luxembourg)', price: 68.01 },
  { id: 'guenange', name: 'Guenange (France)', price: 88.10 },
  { id: 'guerlange', name: 'Guerlange (Belgique)', price: 52.67 },
  { id: 'habay', name: 'Habay (Belgique)', price: 81.70 },
  { id: 'hachy', name: 'Hachy (Belgique)', price: 76.84 },
  { id: 'hagelsdorf', name: 'Hagelsdorf (Luxembourg)', price: 48.70 },
  { id: 'hagondange', name: 'Hagondange (Luxembourg)', price: 83.91 },
  { id: 'hagen_fr', name: 'Hagen (France)', price: 63.71 },
  { id: 'hagen_lux', name: 'Hagen (Luxembourg)', price: 40.09 },
  { id: 'haller', name: 'Haller (Luxembourg)', price: 65.19 },
  { id: 'harlange', name: 'Harlange (Luxembourg)', price: 102.45 },
  { id: 'hassel', name: 'Hassel (Luxembourg)', price: 30.15 },
  { id: 'heffingen', name: 'Heffingen (Luxembourg)', price: 43.29 },
  { id: 'heinerscheid', name: 'Heinerscheid (Luxembourg)', price: 119.23 },
  { id: 'heinsch', name: 'Heinsch (Arlon)', price: 70.77 },
  { id: 'heinstert', name: 'Heinstert (Belgique)', price: 91.96 },
  { id: 'heisdorf', name: 'Heisdorf (Luxembourg)', price: 28.50 },
  { id: 'hellange', name: 'Hellange (Luxembourg)', price: 36.33 },
  { id: 'helmsange', name: 'Helmsange (Luxembourg)', price: 23.75 },
  { id: 'hesperange', name: 'Hesperange (Luxembourg)', price: 15.80 },
  { id: 'hettange', name: 'Hettange (France)', price: 63.27 },
  { id: 'hobscheid', name: 'Hobscheid (Luxembourg)', price: 40.09 },
  { id: 'hockweiler', name: 'Hockweiler (Allemagne)', price: 106.87 },
  { id: 'holzem', name: 'Holzem (Luxembourg)', price: 31.92 },
  { id: 'hosingen', name: 'Hosingen (Luxembourg)', price: 111.39 },
  { id: 'hostert', name: 'Hostert (Luxembourg)', price: 24.96 },
  { id: 'igel', name: 'Igel (Allemagne)', price: 69.78 },
  { id: 'itzig', name: 'Itzig (Luxembourg)', price: 26.84 },
  { id: 'joudreville', name: 'Joudreville (France)', price: 104.33 },
  { id: 'kahler', name: 'Kahler (Luxembourg)', price: 43.84 },
  { id: 'kanfen', name: 'Kanfen (France)', price: 53.99 },
  { id: 'kanzem', name: 'Kanzem (Allemagne)', price: 82.31 },
  { id: 'kayl', name: 'Kayl (Luxembourg)', price: 37.11 },
  { id: 'kehlen', name: 'Kehlen (Luxembourg)', price: 35.89 },
  { id: 'keispelt', name: 'Keispelt (Luxembourg)', price: 30.92 },
  { id: 'kenn', name: 'Kenn (Allemagne)', price: 99.14 },
  { id: 'kirschaumen', name: 'Kirschaumen (Allemagne)', price: 75.08 },
  { id: 'kleinbettingen', name: 'Kleinbettingen (Luxembourg)', price: 62.05 },
  { id: 'knaphoscheid', name: 'Knaphoscheid (Luxembourg)', price: 119.79 },
  { id: 'kockelscheuer', name: 'Kockelscheuer (Luxembourg)', price: 23.09 },
  { id: 'koerich', name: 'Koerich (Luxembourg)', price: 46.93 },
  { id: 'konz', name: 'Konz (Allemagne)', price: 89.21 },
  { id: 'kopstal', name: 'Kopstal (Luxembourg)', price: 28.38 },
  { id: 'kruchten', name: '54675 Kruchten (Allemagne)', price: 95.50 },
  { id: 'la_hulpe', name: 'La Hulpe (Belgique)', price: 360.91 },
  { id: 'langsur', name: 'Langsur (Allemagne)', price: 77.84 },
  { id: 'larochette', name: 'Larochette (Luxembourg)', price: 48.58 },
  { id: 'leithum', name: 'Leithum (Luxembourg)', price: 136.89 },
  { id: 'lenningen', name: 'Lenningen (Luxembourg)', price: 36.22 },
  { id: 'leudelange', name: 'Leudelange (Luxembourg)', price: 23.37 },
  { id: 'lexy', name: 'Lexy / Chenières (France)', price: 90.20 },
  { id: 'libramont', name: 'Libramont (Belgique)', price: 141.42 },
  { id: 'liege', name: 'Liège, Consulat du Maroc', price: 262.90 },
  { id: 'limburg', name: 'Limburg (Allemagne)', price: 387.23 },
  { id: 'lintgen', name: 'Lintgen (Luxembourg)', price: 34.46 },
  { id: 'livange', name: 'Livange (Luxembourg)', price: 30.15 },
  { id: 'longlier', name: 'Longlier (Belgique)', price: 126.29 },
  { id: 'longwy', name: 'Longwy (France)', price: 75.96 },
  { id: 'lorentzweiler', name: 'Lorentzweiler (Luxembourg)', price: 24.52 },
  { id: 'lottert', name: 'Lottert (Belgique)', price: 70.36 },
  { id: 'machtum', name: 'Machtum (Luxembourg)', price: 53.22 },
  { id: 'maidieres', name: 'Maidières (Luxembourg)', price: 165.15 },
  { id: 'mamer', name: 'Mamer, Capellen (Luxembourg)', price: 31.21 },
  { id: 'manternach', name: 'Manternach (Luxembourg)', price: 55.65 },
  { id: 'marche_famenne', name: 'Marche-en-Famenne (Belgique)', price: 210.07 },
  { id: 'marienthal', name: 'Marienthal (Luxembourg)', price: 44.28 },
  { id: 'martelange', name: 'Martelange (Luxembourg)', price: 94.50 },
  { id: 'medernach', name: 'Medernach (Luxembourg)', price: 39.75 },
  { id: 'meispelt', name: 'Meispelt (Luxembourg)', price: 37.22 },
  { id: 'meix_le_tige', name: 'Meix le Tige (France)', price: 84.90 },
  { id: 'mensdorf', name: 'Mensdorf (Luxembourg)', price: 38.43 },
  { id: 'menskirch', name: 'Menskirch (France)', price: 105.10 },
  { id: 'merchweiler', name: 'Merchweiler (Allemagne)', price: 178.37 },
  { id: 'mercy_le_haut', name: 'Mercy-le-haut (France)', price: 85.87 },
  { id: 'mersch', name: 'Mersch (Luxembourg)', price: 42.62 },
  { id: 'merter', name: 'Merter (Luxembourg)', price: 60.51 },
  { id: 'mertzig', name: 'Mertzig (Luxembourg)', price: 73.31 },
  { id: 'messancy', name: 'Messancy (France)', price: 62.71 },
  { id: 'mettlach', name: 'Mettlach (Allemagne)', price: 84.90 },
  { id: 'mettendorf', name: 'Mettendorf (Allemagne)', price: 89.21 },
  { id: 'metz', name: 'Metz (France)', price: 110.40 },
  { id: 'metzervisse', name: 'Metzervisse (France)', price: 80.37 },
  { id: 'moersdorf', name: 'Moersdorf (Luxembourg)', price: 71.54 },
  { id: 'mondelange', name: 'Mondelange (France)', price: 85.67 },
  { id: 'mondercange', name: 'Mondercange (Luxembourg)', price: 38.98 },
  { id: 'mondorf', name: 'Mondorf (Luxembourg)', price: 46.05 },
  { id: 'mortinsart', name: 'Mortinsart (Belgique)', price: 84.79 },
  { id: 'moutfort', name: 'Moutfort (Luxembourg)', price: 24.59 },
  { id: 'mullendorf', name: 'Mullendorf (Luxembourg)', price: 28.38 },
  { id: 'munsbach', name: 'Munsbach, Niederanven (Luxembourg)', price: 31.10 },
  { id: 'musson', name: 'Musson (Belgique)', price: 71.54 },
  { id: 'mussy_la_ville', name: 'Mussy-la-ville (Belgique)', price: 77.06 },
  { id: 'nagem', name: 'Nagem (Luxembourg)', price: 64.48 },
  { id: 'nancy', name: 'Nancy (Luxembourg)', price: 186.99 },
  { id: 'nennig', name: 'Nennig (Allemagne)', price: 47.59 },
  { id: 'neufchef', name: 'Neufchef (France)', price: 83.13 },
  { id: 'niederdonven', name: 'Niederdonven (Luxembourg)', price: 53.11 },
  { id: 'niederkorn', name: 'Niederkorn (Luxembourg)', price: 52.34 },
  { id: 'nittel', name: 'Nittel (Allemagne)', price: 63.71 },
  { id: 'noertzange', name: 'Noertzange (Luxembourg)', price: 50.24 },
  { id: 'norroy_le_veneur', name: 'Norroy-le-Veneur (France)', price: 106.87 },
  { id: 'nospelt', name: 'Nospelt (Luxembourg)', price: 38.98 },
  { id: 'oberanven', name: 'Oberanven (Luxembourg)', price: 33.68 },
  { id: 'oberpallen', name: 'Oberpallen (Luxembourg)', price: 66.25 },
  { id: 'oetrange', name: 'Oetrange (Luxembourg)', price: 27.39 },
  { id: 'olingen', name: 'Olingen (Luxembourg)', price: 37.99 },
  { id: 'perl', name: 'Perl (Allemagne)', price: 55.65 },
  { id: 'perle', name: 'Perlé (Luxembourg)', price: 92.74 },
  { id: 'petit_nobressart', name: 'Petit Nobressart Ell (Luxembourg)', price: 85.67 },
  { id: 'pommerloch', name: 'Pommerloch (Luxembourg)', price: 106.87 },
  { id: 'pontpierre', name: 'Pontpierre (Luxembourg)', price: 35.45 },
  { id: 'preizerdaul', name: 'Preizerdaul (Luxembourg)', price: 59.18 },
  { id: 'rambrouch', name: 'Rambrouch (Luxembourg)', price: 71.54 },
  { id: 'rameldange', name: 'Rameldange (Luxembourg)', price: 25.18 },
  { id: 'reckange_mess', name: 'Reckange/Mess (Luxembourg)', price: 37.22 },
  { id: 'redange_attert', name: 'Redange sur Attert (Luxembourg)', price: 62.45 },
  { id: 'remerschen', name: 'Remerschen (Luxembourg)', price: 56.64 },
  { id: 'remich', name: 'Remich, Mondorf', price: 45.56 },
  { id: 'reuland', name: 'Reuland (Luxembourg)', price: 43.29 },
  { id: 'rippig', name: 'Rippig (Luxembourg)', price: 51.34 },
  { id: 'rippweiler', name: 'Rippweiler (Luxembourg)', price: 48.58 },
  { id: 'robelmont', name: 'Robelmont (Belgique)', price: 106.87 },
  { id: 'rodange', name: 'Rodange (Luxembourg)', price: 55.65 },
  { id: 'rodemack', name: 'Rodemack (France)', price: 58.41 },
  { id: 'roeser', name: 'Roeser (Luxembourg)', price: 28.72 },
  { id: 'rollingen', name: 'Rollingen (Luxembourg)', price: 39.31 },
  { id: 'rood_syre', name: 'Rood sur Syre (Luxembourg)', price: 40.75 },
  { id: 'rosport', name: 'Rosport (Luxembourg)', price: 76.84 },
  { id: 'roussy_village', name: 'Roussy-le-Village (Luxembourg)', price: 45.15 },
  { id: 'rumelange', name: 'Rumelange (Luxembourg)', price: 41.52 },
  { id: 'russange', name: 'Russange (France)', price: 48.03 },
  { id: 'saarbrucken', name: 'Saarbrücken (Allemagne)', price: 168.68 },
  { id: 'saeul', name: 'Saeul (Luxembourg)', price: 53.11 },
  { id: 'saint_leger', name: 'Saint Leger (Belgique)', price: 95.50 },
  { id: 'saint_mard', name: 'Saint-Mard (Belgique)', price: 103.33 },
  { id: 'sainte_marie', name: 'Sainte-Marie-sur-Semois (Luxembourg)', price: 90.97 },
  { id: 'sampon', name: 'Sampon (Belgique)', price: 73.31 },
  { id: 'sandweiler', name: 'Sandweiler (Luxembourg)', price: 25.18 },
  { id: 'sanem', name: 'Sanem (Luxembourg)', price: 41.52 },
  { id: 'scheidgen', name: 'Scheidgen (Luxembourg)', price: 52.12 },
  { id: 'schengen', name: 'Schengen (Luxembourg)', price: 57.42 },
  { id: 'schifflange', name: 'Schifflange (Luxembourg)', price: 37.66 },
  { id: 'schoos', name: 'Schoos (Luxembourg)', price: 43.29 },
  { id: 'schouweiler', name: 'Schouweiler (Luxembourg)', price: 35.45 },
  { id: 'schuttrange', name: 'Schuttrange (Luxembourg)', price: 25.74 },
  { id: 'schwebsange', name: 'Schwebsange (Luxembourg)', price: 54.88 },
  { id: 'schweich', name: 'Schweich (Allemagne)', price: 103.55 },
  { id: 'selange', name: 'Sélange (Belgique)', price: 67.24 },
  { id: 'senningerberg', name: 'Senningerberg (Luxembourg)', price: 22.16 },
  { id: 'septfontaines', name: 'Septfontaines (Luxembourg)', price: 42.62 },
  { id: 'sierck_les_bains', name: 'Sierck-les Bains (France)', price: 66.25 },
  { id: 'steinfort', name: 'Steinfort (Luxembourg)', price: 40.09 },
  { id: 'steinsel', name: 'Steinsel (Luxembourg)', price: 29.05 },
  { id: 'sweich', name: 'Sweich (Luxembourg)', price: 48.58 },
  { id: 'syren', name: 'Syren (Luxembourg)', price: 31.92 },
  { id: 'talange', name: 'Talange (France)', price: 87.44 },
  { id: 'tawern', name: 'Tawern (Allemagne)', price: 68.01 },
  { id: 'tellin', name: 'Tellin (Belgique)', price: 188.11 },
  { id: 'terville', name: 'Terville (France)', price: 74.30 },
  { id: 'thill', name: 'Thill (France)', price: 61.94 },
  { id: 'thionville', name: 'Thionville (France)', price: 70.66 },
  { id: 'tontelange', name: 'Tontelange (Belgique)', price: 73.31 },
  { id: 'trier', name: 'Trier (Allemagne)', price: 89.21 },
  { id: 'trierweiler', name: 'Trierweiler (Allemagne)', price: 91.96 },
  { id: 'trintange', name: 'Trintange (Luxembourg)', price: 27.39 },
  { id: 'troisvierges', name: 'Troisvierges (Luxembourg)', price: 135.12 },
  { id: 'tuntange', name: 'Tuntange (Luxembourg)', price: 35.56 },
  { id: 'uebersyren', name: 'Uebersyren (Luxembourg)', price: 46.98 },
  { id: 'useldange', name: 'Useldange (Luxembourg)', price: 59.18 },
  { id: 'utrecht', name: 'Utrecht (Pay-Bas)', price: 647.03 },
  { id: 'val_de_briey', name: 'Val de briey (France)', price: 96.27 },
  { id: 'vance', name: 'Vance (Belgique)', price: 86.67 },
  { id: 'vianden', name: 'Vianden (Luxembourg)', price: 92.63 },
  { id: 'villers_montagne', name: 'Villers la Montagne (France)', price: 73.64 },
  { id: 'virton', name: 'Virton (saint-Mard) (Belgique)', price: 94.50 },
  { id: 'vise', name: 'Visé (Belgique)', price: 325.86 },
  { id: 'vitry_orne', name: 'Vitry sur Orne (Luxembourg)', price: 77.95 },
  { id: 'volmerange_mines', name: 'Volmerange-les-Mines (Luxembourg)', price: 53.11 },
  { id: 'volstroff', name: 'Volstroff (France)', price: 82.03 },
  { id: 'vresse_semois', name: 'Vresse sur semois (Belgique)', price: 193.88 },
  { id: 'wahl', name: 'Wahl (Luxembourg)', price: 76.71 },
  { id: 'waldbredimus', name: 'Waldbredimus (Luxembourg)', price: 36.77 },
  { id: 'walferdange', name: 'Walferdange (Luxembourg)', price: 24.85 },
  { id: 'wasserbillig', name: 'Wasserbillig (Luxembourg)', price: 63.27 },
  { id: 'wecker', name: 'Wecker (Luxembourg)', price: 48.70 },
  { id: 'weiler_la_tour', name: 'Weiler la Tour (Luxembourg)', price: 30.48 },
  { id: 'weiskirchen', name: 'Weiskirchen (Allemagne)', price: 109.07 },
  { id: 'weiswampach', name: 'Weiswampach (Luxembourg)', price: 129.83 },
  { id: 'wellen', name: 'Wellen (Allemagne)', price: 61.94 },
  { id: 'wemperhardt', name: 'Wemperhardt (Luxembourg)', price: 139.76 },
  { id: 'wickrange', name: 'Wickrange (Luxembourg)', price: 30.73 },
  { id: 'wiltz', name: 'Wiltz (Luxembourg)', price: 106.87 },
  { id: 'wilwerdange', name: 'Wilwerdange (Luxembourg)', price: 142.19 },
  { id: 'wincheringen', name: 'Wincheringen (Luxembourg)', price: 58.41 },
  { id: 'windhof', name: 'Windhof, Junglinster, Notaire Kolbach', price: 34.74 },
  { id: 'wintrange', name: 'Wintrange (Luxembourg)', price: 54.88 },
  { id: 'wormeldange', name: 'Wormeldange (Luxembourg)', price: 53.11 },
  { id: 'yutz', name: 'Yutz (France)', price: 78.34 },
  { id: 'zittig', name: 'Zittig (Luxembourg)', price: 54.88 },
  { id: 'zoufftgen', name: 'Zoufftgen (France)', price: 53.99 },
];

export const MOCK_CLIENTS: Client[] = [
  ...IMPORTED_CLIENTS
];

export const MOCK_LOCATIONS: SavedLocation[] = [
  { id: 'l1', name: 'CDG Airport', address: 'Roissy Charles de Gaulle Airport, Terminal 2E' },
  { id: 'l2', name: 'Orly Airport', address: 'Orly Airport, Terminal 4' },
  { id: 'l3', name: 'Gare du Nord', address: '18 Rue de Dunkerque, 75010 Paris' },
  { id: 'l4', name: 'La Défense', address: 'Grande Arche, Puteaux' },
];

export const DEFAULT_SETTINGS: GlobalSettings = {
  urgency_coefficient: 35,
  precise_time_fee: 35,   
  volume_coefficient: 35,
  weekend_coefficient: 50,
  default_fuel_surcharge_percent: 7.75, 
  vat_percent: 17.0,
  useDeliveryNoteNumbering: false,
  deliveryNoteStartNumber: 1,
  apostille_price: 5,
  customRules: [],
  zone_to_zone_deduction: true,
  zone_to_zone_deduction_type: 'zone',
  zone_to_zone_deduction_value: 1,
  
  zone_to_hors_zone_deduction: true,
  zone_to_hors_zone_deduction_type: 'zone',
  zone_to_hors_zone_deduction_value: 1,
  
  hors_zone_to_hors_zone_deduction: false,
  hors_zone_to_hors_zone_deduction_type: 'zone',
  hors_zone_to_hors_zone_deduction_value: 1,
  
  return_trip_percent: 35
};

export const MASTER_TARIFFS: TariffItem[] = [
    ...ZONES.map(z => ({ ...z, id: `zone_${z.id}`, category: 'zone' as const })),
    ...FIXED_DESTINATIONS.map(d => ({ ...d, category: 'destination' as const })),
    ...SPECIAL_ROUTES.map(r => ({ ...r, category: 'route' as const })),
    { id: 'base_deduction', name: 'Déduction Base (Formule Zone) -12.22€', price: -12.22, category: 'special' as const },
];

export const COUNTRY_CODES = [
    { code: '+352', country: 'Luxembourg', flag: '🇱🇺' },
    { code: '+33', country: 'France', flag: '🇫🇷' },
    { code: '+32', country: 'Belgium', flag: '🇧🇪' },
    { code: '+49', country: 'Germany', flag: '🇩🇪' },
    { code: '+351', country: 'Portugal', flag: '🇵🇹' },
    { code: '+34', country: 'Spain', flag: '🇪🇸' },
    { code: '+39', country: 'Italy', flag: '🇮🇹' },
    { code: '+41', country: 'Switzerland', flag: '🇨🇭' },
    { code: '+44', country: 'United Kingdom', flag: '🇬🇧' },
    { code: '+31', country: 'Netherlands', flag: '🇳🇱' },
    { code: '+43', country: 'Austria', flag: '🇦🇹' },
    { code: '+45', country: 'Denmark', flag: '🇩🇰' },
    { code: '+46', country: 'Sweden', flag: '🇸🇪' },
    { code: '+47', country: 'Norway', flag: '🇳🇴' },
    { code: '+358', country: 'Finland', flag: '🇫🇮' },
    { code: '+353', country: 'Ireland', flag: '🇮🇪' },
    { code: '+48', country: 'Poland', flag: '🇵🇱' },
    { code: '+420', country: 'Czech Republic', flag: '🇨🇿' },
    { code: '+30', country: 'Greece', flag: '🇬🇷' },
    { code: '+36', country: 'Hungary', flag: '🇭🇺' },
    { code: '+40', country: 'Romania', flag: '🇷🇴' },
    { code: '+1', country: 'USA / Canada', flag: '🇺🇸' },
    { code: '+86', country: 'China', flag: '🇨🇳' },
    { code: '+91', country: 'India', flag: '🇮🇳' },
    { code: '+971', country: 'UAE', flag: '🇦🇪' },
    { code: '+55', country: 'Brazil', flag: '🇧🇷' },
    { code: '+81', country: 'Japan', flag: '🇯🇵' },
    { code: '+82', country: 'South Korea', flag: '🇰🇷' },
    { code: '+61', country: 'Australia', flag: '🇦🇺' },
    { code: '+64', country: 'New Zealand', flag: '🇳🇿' },
    { code: '+27', country: 'South Africa', flag: '🇿🇦' },
    { code: '+20', country: 'Egypt', flag: '🇪🇬' },
    { code: '+90', country: 'Turkey', flag: '🇹🇷' },
    { code: '+966', country: 'Saudi Arabia', flag: '🇸🇦' },
    { code: '+65', country: 'Singapore', flag: '🇸🇬' },
    { code: '+66', country: 'Thailand', flag: '🇹🇭' },
    { code: '+84', country: 'Vietnam', flag: '🇻🇳' },
    { code: '+62', country: 'Indonesia', flag: '🇮🇩' },
    { code: '+60', country: 'Malaysia', flag: '🇲🇾' },
    { code: '+63', country: 'Philippines', flag: '🇵🇭' },
    { code: '+52', country: 'Mexico', flag: '🇲🇽' },
    { code: '+54', country: 'Argentina', flag: '🇦🇷' },
    { code: '+57', country: 'Colombia', flag: '🇨🇴' },
    { code: '+56', country: 'Chile', flag: '🇨🇱' },
    { code: '+212', country: 'Morocco', flag: '🇲🇦' },
    { code: '+213', country: 'Algeria', flag: '🇩🇿' },
    { code: '+216', country: 'Tunisia', flag: '🇹🇳' },
];
